import type { FraudCaseRepository, AtomicResult, CreateCaseResult, AddEvidenceResult, CreateExtractionResult, CreateReviewResult } from "../fraud-case-repository";
import type { AddInlineEvidenceCommand, CaseCustomerContext, CasePayment, ExtractionReviewRecord, ExtractionRunRecord, ExtractionTransitionCommand, FraudCaseWorkflow, NewCaseEvent, NewFraudCaseWorkflow, RemoveEvidenceCommand, SaveReportCommand, SubmitCaseCommand } from "../fraud-case-types";

const clone = <T>(value: T): T => structuredClone(value);
export class InMemoryFraudCaseRepository implements FraudCaseRepository {
  private readonly cases = new Map<string, FraudCaseWorkflow>();
  private readonly payments = new Map<string, CasePayment>();
  constructor(private readonly context: CaseCustomerContext | null, payments: readonly CasePayment[] = []) { for (const payment of payments) this.payments.set(payment.id, clone(payment)); }
  private appendEvent(item: FraudCaseWorkflow, event: NewCaseEvent): void { item.events.push({ ...clone(event), eventSequence: item.events.length + 1 }); }
  /** Test-fixture seam for states whose production creators arrive in Phase 3. */
  addEvidenceFixture(caseId: string, evidence: FraudCaseWorkflow["evidenceItems"][number]): void {
    const workflow = this.cases.get(caseId);
    if (!workflow) throw new Error("Test fraud-case fixture does not exist.");
    workflow.evidenceItems.push(clone(evidence));
  }
  async loadCustomerContext() { return clone(this.context); }
  async loadOwnedPayment(paymentId: string, accountId: string) { const value = this.payments.get(paymentId); return value?.accountId === accountId ? clone(value) : null; }
  async findCaseByPaymentId(paymentId: string, accountId: string) { const found = [...this.cases.values()].find((item) => item.fraudCase.paymentId === paymentId && item.payment.accountId === accountId); return found ? clone(found) : null; }
  async loadCase(caseId: string, accountId: string) { const value = this.cases.get(caseId); return value?.payment.accountId === accountId ? clone(value) : null; }
  async createCaseAtomically(input: NewFraudCaseWorkflow, accountId: string): Promise<CreateCaseResult> {
    if ([...this.cases.values()].some((item) => item.fraudCase.paymentId === input.fraudCase.paymentId)) return { kind: "PAYMENT_RACE" };
    const payment = this.payments.get(input.fraudCase.paymentId); if (!payment || payment.accountId !== accountId || payment.status !== "SETTLED") return { kind: "PAYMENT_RACE" };
    this.cases.set(input.fraudCase.id, clone({ fraudCase: input.fraudCase, payment, report: input.report, evidenceItems: [], extractionRuns: [], extractionReviews: [], events: [{ ...input.event, eventSequence: 1 }] })); return { kind: "CREATED" };
  }
  async saveReportAtomically(command: SaveReportCommand): Promise<AtomicResult> { const item = this.cases.get(command.caseId); if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || item.report.version !== command.expectedVersion) return { kind: "CONFLICT" }; item.report = { ...clone(command.report), caseId: item.report.caseId, version: item.report.version + 1, createdAt: item.report.createdAt, updatedAt: command.updatedAt }; item.fraudCase.updatedAt = command.updatedAt; this.appendEvent(item, command.event); return { kind: "APPLIED" }; }
  async findEvidenceByCreationKey(key: string, accountId: string) { for (const item of this.cases.values()) { if (item.payment.accountId === accountId) { const found = item.evidenceItems.find((evidence) => evidence.creationIdempotencyKey === key); if (found) return clone(found); } } return null; }
  async addInlineEvidenceAtomically(command: AddInlineEvidenceCommand): Promise<AddEvidenceResult> { const item = this.cases.get(command.evidence.caseId); if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT") return { kind: "CONFLICT" }; if ([...this.cases.values()].some((workflow) => workflow.evidenceItems.some((evidence) => evidence.creationIdempotencyKey === command.evidence.creationIdempotencyKey))) return { kind: "IDEMPOTENCY_RACE" }; if (item.evidenceItems.filter((evidence) => evidence.status !== "REMOVED").length >= 10) return { kind: "LIMIT" }; item.evidenceItems.push(clone(command.evidence)); this.appendEvent(item, command.event); item.fraudCase.updatedAt = command.evidence.updatedAt; return { kind: "CREATED" }; }
  async removeEvidenceAtomically(command: RemoveEvidenceCommand): Promise<AtomicResult> { const item = this.cases.get(command.caseId); const evidence = item?.evidenceItems.find((candidate) => candidate.id === command.evidenceId); if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || !evidence || evidence.status !== command.expectedStatus || !["AWAITING_UPLOAD", "READY", "REJECTED"].includes(evidence.status)) return { kind: "CONFLICT" }; evidence.status = "REMOVED"; evidence.updatedAt = command.updatedAt; item.fraudCase.updatedAt = command.updatedAt; this.appendEvent(item, command.event); return { kind: "APPLIED" }; }
  async findExtractionByIdempotencyKey(key: string, accountId: string) { for (const item of this.cases.values()) { if (item.payment.accountId === accountId) { const found = item.extractionRuns.find((run) => run.idempotencyKey === key); if (found) return clone(found); } } return null; }
  async createExtractionRunAtomically(run: ExtractionRunRecord, caseId: string, accountId: string, event: NewCaseEvent): Promise<CreateExtractionResult> { const item = this.cases.get(caseId); const evidence = item?.evidenceItems.find((entry) => entry.id === run.evidenceItemId); if (!item || item.payment.accountId !== accountId || item.fraudCase.status !== "DRAFT" || evidence?.status !== "READY" || evidence.sha256 !== run.evidenceSha256) return { kind: "CONFLICT" }; if ([...this.cases.values()].some((workflow) => workflow.extractionRuns.some((entry) => entry.idempotencyKey === run.idempotencyKey))) return { kind: "IDEMPOTENCY_RACE" }; if (item.extractionRuns.some((entry) => entry.evidenceItemId === run.evidenceItemId && entry.evidenceSha256 === run.evidenceSha256 && ["PENDING", "PROCESSING", "COMPLETED"].includes(entry.status))) return { kind: "CONFLICT" }; item.extractionRuns.push(clone(run)); this.appendEvent(item, event); return { kind: "CREATED" }; }
  async transitionExtractionAtomically(command: ExtractionTransitionCommand): Promise<AtomicResult> { const item = this.cases.get(command.caseId); const run = item?.extractionRuns.find((entry) => entry.id === command.runId); if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || !run || run.status !== command.fromStatus) return { kind: "CONFLICT" }; if (command.run.status === "COMPLETED" && item.extractionRuns.some((entry) => entry.id !== run.id && entry.evidenceItemId === run.evidenceItemId && entry.evidenceSha256 === run.evidenceSha256 && entry.status === "COMPLETED")) return { kind: "CONFLICT" }; Object.assign(run, clone(command.run)); this.appendEvent(item, command.event); return { kind: "APPLIED" }; }
  async createExtractionReviewAtomically(review: ExtractionReviewRecord, caseId: string, accountId: string, event: NewCaseEvent): Promise<CreateReviewResult> { const item = this.cases.get(caseId); const run = item?.extractionRuns.find((entry) => entry.id === review.extractionRunId); if (!item || item.payment.accountId !== accountId || item.fraudCase.status !== "DRAFT" || run?.status !== "COMPLETED") return { kind: "CONFLICT" }; if (item.extractionReviews.some((entry) => entry.extractionRunId === run.id)) return { kind: "EXISTS" }; item.extractionReviews.push(clone(review)); this.appendEvent(item, event); return { kind: "CREATED" }; }
  async submitCaseAtomically(command: SubmitCaseCommand): Promise<AtomicResult> { const item = this.cases.get(command.caseId); if (!item || item.payment.accountId !== command.accountId) return { kind: "CONFLICT" }; if (item.fraudCase.status === "SUBMITTED") return { kind: "CONFLICT" }; if (item.report.version !== command.expectedReportVersion || item.payment.status !== "SETTLED" || item.evidenceItems.some((evidence) => evidence.status === "AWAITING_UPLOAD" || evidence.status === "VALIDATING") || item.extractionRuns.some((run) => run.status === "COMPLETED" && !item.extractionReviews.some((review) => review.extractionRunId === run.id))) return { kind: "CONFLICT" }; item.fraudCase.status = "SUBMITTED"; item.fraudCase.submittedAt = command.submittedAt; item.fraudCase.updatedAt = command.submittedAt; item.fraudCase.submissionIdempotencyKey = command.idempotencyKey; this.appendEvent(item, command.event); return { kind: "APPLIED" }; }
}
