import { MAX_EVIDENCE_ITEMS_PER_CASE, MAX_FILE_EVIDENCE_ITEMS_PER_CASE, MAX_STORED_FILE_BYTES_PER_CASE } from "../../../evidence/domain/evidence";
import type { FraudCaseRepository, AtomicResult, CreateCaseResult, AddEvidenceResult, CreateExtractionResult, CreateReviewResult, CreateFileEvidenceResult, ReserveFileMetadataResult } from "../fraud-case-repository";
import type { AddInlineEvidenceCommand, CaseCustomerContext, CasePayment, ClaimFileValidationCommand, CreateFileEvidenceCommand, ExtractionReviewRecord, ExtractionRunRecord, ExtractionTransitionCommand, FinalizeFileReadyCommand, FinalizeFileRejectedCommand, FraudCaseWorkflow, NewCaseEvent, NewFraudCaseWorkflow, PrepareFileUploadGrantCommand, ReclaimFileValidationCommand, RemoveEvidenceCommand, ReserveFileMetadataCommand, SaveReportCommand, SubmitCaseCommand } from "../fraud-case-types";

const clone = <T>(value: T): T => structuredClone(value);
export class InMemoryFraudCaseRepository implements FraudCaseRepository {
  private readonly cases = new Map<string, FraudCaseWorkflow>();
  private readonly payments = new Map<string, CasePayment>();
  constructor(private readonly context: CaseCustomerContext | null, payments: readonly CasePayment[] = []) { for (const payment of payments) this.payments.set(payment.id, clone(payment)); }
  private appendEvent(item: FraudCaseWorkflow, event: NewCaseEvent): void { item.events.push({ ...clone(event), eventSequence: item.events.length + 1 }); }
  /** Test-fixture seam for states whose production creators arrive in Phase 3. */
  addEvidenceFixture(caseId: string, evidence: FraudCaseWorkflow["evidenceItems"][number]): void {
    const workflow = this.cases.get(caseId);
    if (!workflow) throw new Error("Test fraud-case fixture does not exist.");
    workflow.evidenceItems.push(clone(evidence));
  }
  async loadCustomerContext() { return clone(this.context); }
  async loadOwnedPayment(paymentId: string, accountId: string) { const value = this.payments.get(paymentId); return value?.accountId === accountId ? clone(value) : null; }
  async findCaseByPaymentId(paymentId: string, accountId: string) { const found = [...this.cases.values()].find((item) => item.fraudCase.paymentId === paymentId && item.payment.accountId === accountId); return found ? clone(found) : null; }
  async loadCase(caseId: string, accountId: string) { const value = this.cases.get(caseId); return value?.payment.accountId === accountId ? clone(value) : null; }
  async createCaseAtomically(input: NewFraudCaseWorkflow, accountId: string): Promise<CreateCaseResult> {
    if ([...this.cases.values()].some((item) => item.fraudCase.paymentId === input.fraudCase.paymentId)) return { kind: "PAYMENT_RACE" };
    const payment = this.payments.get(input.fraudCase.paymentId); if (!payment || payment.accountId !== accountId || payment.status !== "SETTLED") return { kind: "PAYMENT_RACE" };
    this.cases.set(input.fraudCase.id, clone({ fraudCase: input.fraudCase, payment, report: input.report, evidenceItems: [], extractionRuns: [], extractionReviews: [], events: [{ ...input.event, eventSequence: 1 }] })); return { kind: "CREATED" };
  }
  async saveReportAtomically(command: SaveReportCommand): Promise<AtomicResult> { const item = this.cases.get(command.caseId); if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || item.report.version !== command.expectedVersion) return { kind: "CONFLICT" }; item.report = { ...clone(command.report), caseId: item.report.caseId, version: item.report.version + 1, createdAt: item.report.createdAt, updatedAt: command.updatedAt }; item.fraudCase.updatedAt = command.updatedAt; this.appendEvent(item, command.event); return { kind: "APPLIED" }; }
  async findEvidenceByCreationKey(key: string, accountId: string) { for (const item of this.cases.values()) { if (item.payment.accountId === accountId) { const found = item.evidenceItems.find((evidence) => evidence.creationIdempotencyKey === key); if (found) return clone(found); } } return null; }
  async findEvidenceByUploadKey(key: string, accountId: string) { for (const item of this.cases.values()) { if (item.payment.accountId === accountId) { const found = item.evidenceItems.find((evidence) => evidence.uploadIdempotencyKey === key); if (found) return clone(found); } } return null; }
  async addInlineEvidenceAtomically(command: AddInlineEvidenceCommand): Promise<AddEvidenceResult> { const item = this.cases.get(command.evidence.caseId); if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT") return { kind: "CONFLICT" }; if ([...this.cases.values()].some((workflow) => workflow.evidenceItems.some((evidence) => evidence.creationIdempotencyKey === command.evidence.creationIdempotencyKey))) return { kind: "IDEMPOTENCY_RACE" }; if (item.evidenceItems.filter((evidence) => evidence.status !== "REMOVED").length >= 10) return { kind: "LIMIT" }; item.evidenceItems.push(clone(command.evidence)); this.appendEvent(item, command.event); item.fraudCase.updatedAt = command.evidence.updatedAt; return { kind: "CREATED" }; }
  async createFileEvidenceAtomically(command: CreateFileEvidenceCommand): Promise<CreateFileEvidenceResult> {
    const item = this.cases.get(command.evidence.caseId);
    if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT") return { kind: "CONFLICT" };
    if ([...this.cases.values()].some((workflow) => workflow.evidenceItems.some((evidence) => evidence.uploadIdempotencyKey === command.evidence.uploadIdempotencyKey))) return { kind: "IDEMPOTENCY_RACE" };
    const active = item.evidenceItems.filter((evidence) => evidence.status !== "REMOVED");
    if (active.length >= MAX_EVIDENCE_ITEMS_PER_CASE) return { kind: "TOTAL_LIMIT" };
    if (active.filter((evidence) => evidence.kind === "FILE").length >= MAX_FILE_EVIDENCE_ITEMS_PER_CASE) return { kind: "FILE_LIMIT" };
    item.evidenceItems.push(clone(command.evidence)); item.fraudCase.updatedAt = command.evidence.updatedAt; this.appendEvent(item, command.event); return { kind: "CREATED" };
  }
  async prepareFileUploadGrantAtomically(command: PrepareFileUploadGrantCommand): Promise<AtomicResult> {
    const item = this.cases.get(command.caseId); const evidence = item?.evidenceItems.find((entry) => entry.id === command.evidenceId);
    if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || evidence?.kind !== "FILE" || evidence.status !== "AWAITING_UPLOAD") return { kind: "CONFLICT" };
    evidence.uploadExpiresAt = clone(command.expiresAt); evidence.updatedAt = clone(command.updatedAt); item.fraudCase.updatedAt = clone(command.updatedAt); return { kind: "APPLIED" };
  }
  async claimFileValidationAtomically(command: ClaimFileValidationCommand): Promise<AtomicResult> {
    const item = this.cases.get(command.caseId); const evidence = item?.evidenceItems.find((entry) => entry.id === command.evidenceId);
    if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || evidence?.kind !== "FILE" || evidence.status !== "AWAITING_UPLOAD") return { kind: "CONFLICT" };
    evidence.status = "VALIDATING"; evidence.validationStartedAt = clone(command.validationToken); evidence.uploadedAt = clone(command.uploadedAt); evidence.updatedAt = clone(command.validationToken); item.fraudCase.updatedAt = clone(command.validationToken); this.appendEvent(item, command.event); return { kind: "APPLIED" };
  }
  async reclaimFileValidationAtomically(command: ReclaimFileValidationCommand): Promise<AtomicResult> {
    const item = this.cases.get(command.caseId); const evidence = item?.evidenceItems.find((entry) => entry.id === command.evidenceId);
    if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || evidence?.kind !== "FILE" || evidence.status !== "VALIDATING" || evidence.validationStartedAt?.getTime() !== command.previousToken.getTime() || evidence.validationStartedAt.getTime() > command.staleBefore.getTime() || command.replacementToken.getTime() < evidence.validationStartedAt.getTime() + 1) return { kind: "CONFLICT" };
    evidence.validationStartedAt = clone(command.replacementToken); evidence.updatedAt = clone(command.replacementToken); item.fraudCase.updatedAt = clone(command.replacementToken); this.appendEvent(item, command.event); return { kind: "APPLIED" };
  }
  async reserveFileMetadataAtomically(command: ReserveFileMetadataCommand): Promise<ReserveFileMetadataResult> {
    const item = this.cases.get(command.caseId); const evidence = item?.evidenceItems.find((entry) => entry.id === command.evidenceId);
    if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || evidence?.kind !== "FILE" || evidence.status !== "VALIDATING" || evidence.validationStartedAt?.getTime() !== command.validationToken.getTime()) return { kind: "CONFLICT" };
    const otherBytes = item.evidenceItems.filter((entry) => entry.id !== evidence.id && entry.kind === "FILE" && (entry.status === "READY" || (entry.status === "VALIDATING" && entry.sizeBytes !== null))).reduce((sum, entry) => sum + (entry.sizeBytes ?? 0), 0);
    if (otherBytes + command.metadata.sizeBytes > MAX_STORED_FILE_BYTES_PER_CASE) {
      evidence.status = "REJECTED"; evidence.storageObjectKey = null; evidence.detectedMimeType = null; evidence.sizeBytes = null; evidence.sha256 = null; evidence.safeFailureCode = "CASE_FILE_BYTES_LIMIT_EXCEEDED"; evidence.validatedAt = clone(command.updatedAt); evidence.updatedAt = clone(command.updatedAt); item.fraudCase.updatedAt = clone(command.updatedAt); this.appendEvent(item, { ...command.rejectionEvent, metadata: { simulation: true, failureCode: "CASE_FILE_BYTES_LIMIT_EXCEEDED" } }); return { kind: "REJECTED" };
    }
    evidence.storageObjectKey = command.metadata.storageObjectKey; evidence.detectedMimeType = command.metadata.detectedMimeType; evidence.sizeBytes = command.metadata.sizeBytes; evidence.sha256 = command.metadata.sha256; evidence.updatedAt = clone(command.updatedAt); item.fraudCase.updatedAt = clone(command.updatedAt); return { kind: "RESERVED" };
  }
  async finalizeFileReadyAtomically(command: FinalizeFileReadyCommand): Promise<AtomicResult> {
    const item = this.cases.get(command.caseId); const evidence = item?.evidenceItems.find((entry) => entry.id === command.evidenceId);
    if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || evidence?.kind !== "FILE" || evidence.status !== "VALIDATING" || evidence.validationStartedAt?.getTime() !== command.validationToken.getTime() || evidence.sizeBytes !== command.metadata.sizeBytes || evidence.detectedMimeType !== command.metadata.detectedMimeType || evidence.sha256 !== command.metadata.sha256 || evidence.storageObjectKey !== command.metadata.storageObjectKey) return { kind: "CONFLICT" };
    evidence.status = "READY"; evidence.validatedAt = clone(command.completedAt); evidence.updatedAt = clone(command.completedAt); item.fraudCase.updatedAt = clone(command.completedAt); this.appendEvent(item, command.event); return { kind: "APPLIED" };
  }
  async finalizeFileRejectedAtomically(command: FinalizeFileRejectedCommand): Promise<AtomicResult> {
    const item = this.cases.get(command.caseId); const evidence = item?.evidenceItems.find((entry) => entry.id === command.evidenceId);
    if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || evidence?.kind !== "FILE" || evidence.status !== "VALIDATING" || evidence.validationStartedAt?.getTime() !== command.validationToken.getTime()) return { kind: "CONFLICT" };
    evidence.status = "REJECTED"; evidence.storageObjectKey = null; evidence.detectedMimeType = null; evidence.sizeBytes = null; evidence.sha256 = null; evidence.safeFailureCode = command.safeFailureCode; evidence.validatedAt = clone(command.completedAt); evidence.updatedAt = clone(command.completedAt); item.fraudCase.updatedAt = clone(command.completedAt); this.appendEvent(item, command.event); return { kind: "APPLIED" };
  }
  async removeEvidenceAtomically(command: RemoveEvidenceCommand): Promise<AtomicResult> { const item = this.cases.get(command.caseId); const evidence = item?.evidenceItems.find((candidate) => candidate.id === command.evidenceId); if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || !evidence || evidence.status !== command.expectedStatus || !["AWAITING_UPLOAD", "READY", "REJECTED"].includes(evidence.status)) return { kind: "CONFLICT" }; evidence.status = "REMOVED"; evidence.updatedAt = command.updatedAt; item.fraudCase.updatedAt = command.updatedAt; this.appendEvent(item, command.event); return { kind: "APPLIED" }; }
  async findExtractionByIdempotencyKey(key: string, accountId: string) { for (const item of this.cases.values()) { if (item.payment.accountId === accountId) { const found = item.extractionRuns.find((run) => run.idempotencyKey === key); if (found) return clone(found); } } return null; }
  async createExtractionRunAtomically(run: ExtractionRunRecord, caseId: string, accountId: string, event: NewCaseEvent): Promise<CreateExtractionResult> { const item = this.cases.get(caseId); const evidence = item?.evidenceItems.find((entry) => entry.id === run.evidenceItemId); if (!item || item.payment.accountId !== accountId || item.fraudCase.status !== "DRAFT" || evidence?.status !== "READY" || evidence.sha256 !== run.evidenceSha256) return { kind: "CONFLICT" }; if ([...this.cases.values()].some((workflow) => workflow.extractionRuns.some((entry) => entry.idempotencyKey === run.idempotencyKey))) return { kind: "IDEMPOTENCY_RACE" }; if (item.extractionRuns.some((entry) => entry.evidenceItemId === run.evidenceItemId && entry.evidenceSha256 === run.evidenceSha256 && ["PENDING", "PROCESSING", "COMPLETED"].includes(entry.status))) return { kind: "CONFLICT" }; item.extractionRuns.push(clone(run)); this.appendEvent(item, event); return { kind: "CREATED" }; }
  async transitionExtractionAtomically(command: ExtractionTransitionCommand): Promise<AtomicResult> { const item = this.cases.get(command.caseId); const run = item?.extractionRuns.find((entry) => entry.id === command.runId); if (!item || item.payment.accountId !== command.accountId || item.fraudCase.status !== "DRAFT" || !run || run.status !== command.fromStatus) return { kind: "CONFLICT" }; if (command.run.status === "COMPLETED" && item.extractionRuns.some((entry) => entry.id !== run.id && entry.evidenceItemId === run.evidenceItemId && entry.evidenceSha256 === run.evidenceSha256 && entry.status === "COMPLETED")) return { kind: "CONFLICT" }; Object.assign(run, clone(command.run)); this.appendEvent(item, command.event); return { kind: "APPLIED" }; }
  async createExtractionReviewAtomically(review: ExtractionReviewRecord, caseId: string, accountId: string, event: NewCaseEvent): Promise<CreateReviewResult> { const item = this.cases.get(caseId); const run = item?.extractionRuns.find((entry) => entry.id === review.extractionRunId); if (!item || item.payment.accountId !== accountId || item.fraudCase.status !== "DRAFT" || run?.status !== "COMPLETED") return { kind: "CONFLICT" }; if (item.extractionReviews.some((entry) => entry.extractionRunId === run.id)) return { kind: "EXISTS" }; item.extractionReviews.push(clone(review)); this.appendEvent(item, event); return { kind: "CREATED" }; }
  async submitCaseAtomically(command: SubmitCaseCommand): Promise<AtomicResult> { const item = this.cases.get(command.caseId); if (!item || item.payment.accountId !== command.accountId) return { kind: "CONFLICT" }; if (item.fraudCase.status === "SUBMITTED") return { kind: "CONFLICT" }; if (item.report.version !== command.expectedReportVersion || item.payment.status !== "SETTLED" || item.evidenceItems.some((evidence) => evidence.status === "AWAITING_UPLOAD" || evidence.status === "VALIDATING") || item.extractionRuns.some((run) => run.status === "COMPLETED" && !item.extractionReviews.some((review) => review.extractionRunId === run.id))) return { kind: "CONFLICT" }; item.fraudCase.status = "SUBMITTED"; item.fraudCase.submittedAt = command.submittedAt; item.fraudCase.updatedAt = command.submittedAt; item.fraudCase.submissionIdempotencyKey = command.idempotencyKey; this.appendEvent(item, command.event); return { kind: "APPLIED" }; }
}
