import { describe, expect, it } from "vitest";
import { FraudCaseDomainError } from "../domain/fraud-case-errors";
import { FraudCaseApplicationError } from "./fraud-case-application-errors";
import { InMemoryFraudCaseRepository } from "./testing/in-memory-fraud-case-repository";
import { createOrResumeFraudCase } from "./create-or-resume-fraud-case";
import { saveFraudCaseReport } from "./save-fraud-case-report";
import { addInlineEvidence, removeEvidence } from "./manage-inline-evidence";
import { claimExtractionRun, completeExtractionRun, createExtractionRun, failExtractionRun, reviewExtraction } from "./manage-extractions";
import { submitFraudCase } from "./submit-fraud-case";

const context = { customerId: "10000000-0000-4000-8000-000000000001", accountId: "20000000-0000-4000-8000-000000000001" };
const paymentId = "40000000-0000-4000-8000-000000000001";
const id = (number: number) => `00000000-0000-4000-8000-${String(number).padStart(12, "0")}`;
function harness(status: "SETTLED" | "AUTHORISED" = "SETTLED") {
  const repository = new InMemoryFraudCaseRepository(context, [{ id: paymentId, accountId: context.accountId, beneficiaryId: id(90), beneficiaryName: "Synthetic Beneficiary", amountMinor: 50_000, currencyCode: "GBP", reference: "Synthetic payment", status, createdAt: new Date("2026-07-01T00:00:00Z") }]);
  let sequence = 1; let tick = 0;
  const deps = { repository, uuid: () => id(sequence++), now: () => new Date(Date.parse("2026-08-07T12:00:00.000Z") + tick++) };
  return { repository, deps };
}
const completeReport = { suspectedScamCategory: "INVESTMENT" as const, believedPaymentPurpose: "Investment opportunity", contactChannel: "MESSAGING_APP" as const, firstContactAt: null, discoveredAt: new Date("2026-08-01T10:00:00Z"), discoveryReason: "The promised withdrawal did not arrive.", narrative: "I was contacted about an investment and later became concerned.", pressureOrUrgency: "YES" as const, guaranteedReturns: "YES" as const, toldToIgnoreWarnings: "NO" as const, remoteAccessRequested: "NO" as const, impersonatedOrganisation: " Demo Broker ", additionalSupportRequested: false };
const output = { believedPurpose: null, impersonatedOrganisation: null, pressureOrUrgency: null, guaranteedReturns: null, toldToIgnoreWarnings: null, remoteAccessRequested: null, uncertaintyNotes: [] };
async function draft() { const value = harness(); const workflow = await createOrResumeFraudCase(paymentId, value.deps); return { ...value, workflow }; }

describe("fraud case creation and report persistence", () => {
  it("creates one DRAFT case, version-one report and sequence-one event", async () => { const { deps } = harness(); const workflow = await createOrResumeFraudCase(paymentId, deps); expect(workflow.fraudCase.status).toBe("DRAFT"); expect(workflow.report.version).toBe(1); expect(workflow.events).toMatchObject([{ eventType: "CASE_DRAFT_CREATED", eventSequence: 1 }]); });
  it("resumes rather than duplicates", async () => { const { deps } = harness(); const first = await createOrResumeFraudCase(paymentId, deps); const second = await Promise.all([createOrResumeFraudCase(paymentId, deps), createOrResumeFraudCase(paymentId, deps)]); expect(second.map((item) => item.fraudCase.id)).toEqual([first.fraudCase.id, first.fraudCase.id]); expect(second[0].events).toHaveLength(1); });
  it("rejects a non-settled payment", async () => { const { deps } = harness("AUTHORISED"); await expect(createOrResumeFraudCase(paymentId, deps)).rejects.toMatchObject({ code: "PAYMENT_NOT_REPORTABLE" } satisfies Partial<FraudCaseDomainError>); });
  it("rejects wrong-account and missing context access", async () => { const wrong = new InMemoryFraudCaseRepository(context, [{ id: paymentId, accountId: id(88), beneficiaryId: id(90), beneficiaryName: "Other Beneficiary", amountMinor: 10_000, currencyCode: "GBP", reference: "Synthetic", status: "SETTLED", createdAt: new Date() }]); await expect(createOrResumeFraudCase(paymentId, { repository: wrong })).rejects.toMatchObject({ code: "PAYMENT_NOT_OWNED" }); await expect(createOrResumeFraudCase(paymentId, { repository: new InMemoryFraudCaseRepository(null) })).rejects.toMatchObject({ code: "FRAUD_CASE_CONTEXT_NOT_FOUND" }); });
  it("saves partial drafts and allocates the next event sequence", async () => { const { deps, workflow } = await draft(); const saved = await saveFraudCaseReport({ caseId: workflow.fraudCase.id, expectedVersion: 1, report: { believedPaymentPurpose: "  Deposit  " } }, deps); expect(saved.report).toMatchObject({ believedPaymentPurpose: "Deposit", version: 2 }); expect(saved.events.at(-1)).toMatchObject({ eventType: "REPORT_UPDATED", eventSequence: 2 }); });
  it("rejects stale writes without overwriting or consuming a sequence", async () => { const { deps, repository, workflow } = await draft(); await saveFraudCaseReport({ caseId: workflow.fraudCase.id, expectedVersion: 1, report: { believedPaymentPurpose: "Newest" } }, deps); await expect(saveFraudCaseReport({ caseId: workflow.fraudCase.id, expectedVersion: 1, report: { believedPaymentPurpose: "Stale" } }, deps)).rejects.toMatchObject({ code: "REPORT_STALE" } satisfies Partial<FraudCaseApplicationError>); const latest = await repository.loadCase(workflow.fraudCase.id, context.accountId); expect(latest?.report.believedPaymentPurpose).toBe("Newest"); expect(latest?.events.map((event) => event.eventSequence)).toEqual([1, 2]); });
  it("keeps sequences independent per fraud case", async () => { const secondPayment = { id: id(91), accountId: context.accountId, beneficiaryId: id(3), beneficiaryName: "Second", amountMinor: 5000, currencyCode: "GBP", reference: "Second", status: "SETTLED" as const, createdAt: new Date() }; const firstPayment = { ...secondPayment, id: paymentId }; const repository = new InMemoryFraudCaseRepository(context, [firstPayment, secondPayment]); const deps = { repository, uuid: (() => { let value = 300; return () => id(value++); })(), now: () => new Date("2026-08-08T12:00:00Z") }; const [first, second] = await Promise.all([createOrResumeFraudCase(paymentId, deps), createOrResumeFraudCase(secondPayment.id, deps)]); expect(first.events[0].eventSequence).toBe(1); expect(second.events[0].eventSequence).toBe(1); });
  it("uses sequence rather than equal timestamps for authoritative order", async () => { const value = harness(); const at = new Date("2026-08-08T12:00:00Z"); const deps = { ...value.deps, now: () => at }; const created = await createOrResumeFraudCase(paymentId, deps); await saveFraudCaseReport({ caseId: created.fraudCase.id, expectedVersion: 1, report: { believedPaymentPurpose: "Synthetic" } }, deps); await addInlineEvidence({ caseId: created.fraudCase.id, kind: "PASTED_TEXT", category: "EMAIL", content: "Synthetic", idempotencyKey: id(70) }, deps); const loaded = await value.repository.loadCase(created.fraudCase.id, context.accountId); expect(loaded?.events.every((item) => item.occurredAt.getTime() === at.getTime())).toBe(true); expect(loaded?.events.map((item) => item.eventSequence)).toEqual([1, 2, 3]); });
});

describe("inline evidence", () => {
  it.each(["PASTED_TEXT", "CALL_NOTE"] as const)("stores normalized %s READY with a hash", async (kind) => { const { deps, workflow } = await draft(); const evidence = await addInlineEvidence({ caseId: workflow.fraudCase.id, kind, category: kind === "CALL_NOTE" ? "CALL_NOTE" : "MESSAGE_CONVERSATION", content: " Cafe\u0301\r\nmessage ", idempotencyKey: id(70) }, deps); expect(evidence).toMatchObject({ status: "READY", inlineText: "Café\nmessage" }); expect(evidence.sha256).toMatch(/^[0-9a-f]{64}$/); });
  it("returns the same evidence for an identical request", async () => { const { deps, repository, workflow } = await draft(); const request = { caseId: workflow.fraudCase.id, kind: "PASTED_TEXT" as const, category: "EMAIL" as const, content: "Synthetic text", idempotencyKey: id(70) }; const first = await addInlineEvidence(request, deps); const second = await addInlineEvidence(request, deps); expect(second.id).toBe(first.id); expect((await repository.loadCase(workflow.fraudCase.id, context.accountId))?.evidenceItems).toHaveLength(1); });
  it("rejects a reused key with different content", async () => { const { deps, workflow } = await draft(); const base = { caseId: workflow.fraudCase.id, kind: "PASTED_TEXT" as const, category: "EMAIL" as const, idempotencyKey: id(70) }; await addInlineEvidence({ ...base, content: "First" }, deps); await expect(addInlineEvidence({ ...base, content: "Second" }, deps)).rejects.toMatchObject({ code: "EVIDENCE_IDEMPOTENCY_CONFLICT" }); });
  it("enforces the ten-active-item limit", async () => { const { deps, workflow } = await draft(); for (let index = 0; index < 10; index++) await addInlineEvidence({ caseId: workflow.fraudCase.id, kind: "CALL_NOTE", category: "CALL_NOTE", content: `Note ${index}`, idempotencyKey: id(100 + index) }, deps); await expect(addInlineEvidence({ caseId: workflow.fraudCase.id, kind: "CALL_NOTE", category: "CALL_NOTE", content: "Overflow", idempotencyKey: id(120) }, deps)).rejects.toMatchObject({ code: "EVIDENCE_LIMIT_REACHED" }); });
  it("removes idempotently without consuming another sequence", async () => { const { deps, repository, workflow } = await draft(); const evidence = await addInlineEvidence({ caseId: workflow.fraudCase.id, kind: "CALL_NOTE", category: "CALL_NOTE", content: "Note", idempotencyKey: id(70) }, deps); await removeEvidence({ caseId: workflow.fraudCase.id, evidenceId: evidence.id }, deps); await removeEvidence({ caseId: workflow.fraudCase.id, evidenceId: evidence.id }, deps); const latest = await repository.loadCase(workflow.fraudCase.id, context.accountId); expect(latest?.evidenceItems[0].status).toBe("REMOVED"); expect(latest?.events.map((event) => event.eventSequence)).toEqual([1, 2, 3]); });
});

describe("extraction persistence", () => {
  async function ready() { const value = await draft(); const evidence = await addInlineEvidence({ caseId: value.workflow.fraudCase.id, kind: "PASTED_TEXT", category: "EMAIL", content: "Synthetic message", idempotencyKey: id(70) }, value.deps); return { ...value, evidence }; }
  it("persists PENDING, PROCESSING and COMPLETED lifecycle", async () => { const { deps, workflow, evidence } = await ready(); const run = await createExtractionRun({ caseId: workflow.fraudCase.id, evidenceItemId: evidence.id, evidenceSha256: evidence.sha256!, idempotencyKey: id(71), provider: "fake", model: "deterministic", modelVersion: "1", promptVersion: "v1", schemaVersion: "v1" }, deps); expect(run.status).toBe("PENDING"); expect((await claimExtractionRun(workflow.fraudCase.id, run.id, deps)).status).toBe("PROCESSING"); expect((await completeExtractionRun(workflow.fraudCase.id, run.id, output, deps)).status).toBe("COMPLETED"); });
  it("preserves failed runs and permits a new retry", async () => { const { deps, workflow, evidence } = await ready(); const base = { caseId: workflow.fraudCase.id, evidenceItemId: evidence.id, evidenceSha256: evidence.sha256!, provider: "fake", model: "deterministic", modelVersion: "1", promptVersion: "v1", schemaVersion: "v1" }; const first = await createExtractionRun({ ...base, idempotencyKey: id(71) }, deps); await claimExtractionRun(workflow.fraudCase.id, first.id, deps); await failExtractionRun(workflow.fraudCase.id, first.id, "PROVIDER_UNAVAILABLE", deps); const retry = await createExtractionRun({ ...base, idempotencyKey: id(72) }, deps); expect(retry.id).not.toBe(first.id); expect(retry.status).toBe("PENDING"); });
  it("rejects hash mismatch", async () => { const { deps, workflow, evidence } = await ready(); await expect(createExtractionRun({ caseId: workflow.fraudCase.id, evidenceItemId: evidence.id, evidenceSha256: "a".repeat(64), idempotencyKey: id(71), provider: "fake", model: "m", modelVersion: "1", promptVersion: "v1", schemaVersion: "v1" }, deps)).rejects.toMatchObject({ code: "EXTRACTION_HASH_MISMATCH" }); });
  it("does not reinterpret an extraction idempotency key", async () => { const { deps, workflow, evidence } = await ready(); const base = { caseId: workflow.fraudCase.id, evidenceItemId: evidence.id, evidenceSha256: evidence.sha256!, idempotencyKey: id(71), provider: "fake", model: "m", modelVersion: "1", promptVersion: "v1", schemaVersion: "v1" }; const first = await createExtractionRun(base, deps); expect((await createExtractionRun(base, deps)).id).toBe(first.id); await expect(createExtractionRun({ ...base, model: "different" }, deps)).rejects.toMatchObject({ code: "EXTRACTION_IDEMPOTENCY_CONFLICT" }); });
  it.each(["PENDING", "PROCESSING"] as const)("prevents another active run while one is %s", async (status) => { const { deps, workflow, evidence } = await ready(); const base = { caseId: workflow.fraudCase.id, evidenceItemId: evidence.id, evidenceSha256: evidence.sha256!, provider: "fake", model: "m", modelVersion: "1", promptVersion: "v1", schemaVersion: "v1" }; const first = await createExtractionRun({ ...base, idempotencyKey: id(71) }, deps); if (status === "PROCESSING") await claimExtractionRun(workflow.fraudCase.id, first.id, deps); await expect(createExtractionRun({ ...base, idempotencyKey: id(72) }, deps)).rejects.toMatchObject({ code: "FRAUD_CASE_PERSISTENCE_CONFLICT" }); });
  it("reviews only completed runs and keeps corrections separate", async () => { const { deps, repository, workflow, evidence } = await ready(); const command = { caseId: workflow.fraudCase.id, evidenceItemId: evidence.id, evidenceSha256: evidence.sha256!, idempotencyKey: id(71), provider: "fake", model: "m", modelVersion: "1", promptVersion: "v1", schemaVersion: "v1" }; const run = await createExtractionRun(command, deps); await expect(reviewExtraction({ caseId: workflow.fraudCase.id, runId: run.id, status: "CONFIRMED" }, deps)).rejects.toMatchObject({ code: "CASE_SUBMISSION_BLOCKED" }); await claimExtractionRun(workflow.fraudCase.id, run.id, deps); await completeExtractionRun(workflow.fraudCase.id, run.id, output, deps); const corrected = { ...output, uncertaintyNotes: ["Customer corrected the extraction"] }; await reviewExtraction({ caseId: workflow.fraudCase.id, runId: run.id, status: "CORRECTED", correctedOutput: corrected }, deps); const latest = await repository.loadCase(workflow.fraudCase.id, context.accountId); expect(latest?.extractionRuns[0].machineOutput).toEqual(output); expect(latest?.extractionReviews[0].correctedOutput).toEqual(corrected); });
});

describe("submission", () => {
  async function completeDraft() { const value = await draft(); const workflow = await saveFraudCaseReport({ caseId: value.workflow.fraudCase.id, expectedVersion: 1, report: completeReport }, value.deps); return { ...value, workflow }; }
  it("submits a complete report without evidence once", async () => { const { deps, repository, workflow } = await completeDraft(); const submitted = await submitFraudCase({ caseId: workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, deps); const retry = await submitFraudCase({ caseId: workflow.fraudCase.id, submissionIdempotencyKey: id(81) }, deps); expect(submitted.fraudCase.status).toBe("SUBMITTED"); expect(retry.fraudCase.id).toBe(submitted.fraudCase.id); expect((await repository.loadCase(workflow.fraudCase.id, context.accountId))?.events.map((event) => event.eventSequence)).toEqual([1, 2, 3]); });
  it("blocks incomplete reports", async () => { const { deps, workflow } = await draft(); await expect(submitFraudCase({ caseId: workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, deps)).rejects.toMatchObject({ code: "REPORT_INCOMPLETE" }); });
  it.each(["AWAITING_UPLOAD", "VALIDATING"] as const)("blocks %s evidence", async (status) => { const { deps, repository, workflow } = await completeDraft(); const at = new Date(); repository.addEvidenceFixture(workflow.fraudCase.id, { id: id(200), caseId: workflow.fraudCase.id, kind: "FILE", category: "OTHER_DOCUMENT", status, originalFilename: "synthetic.pdf", storageObjectKey: null, declaredMimeType: "application/pdf", detectedMimeType: null, sizeBytes: null, sha256: null, inlineText: null, capturedAt: null, creationIdempotencyKey: null, uploadIdempotencyKey: id(201), uploadExpiresAt: at, validationStartedAt: status === "VALIDATING" ? at : null, uploadedAt: null, validatedAt: null, safeFailureCode: null, createdAt: at, updatedAt: at }); await expect(submitFraudCase({ caseId: workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, deps)).rejects.toMatchObject({ code: "CASE_SUBMISSION_BLOCKED" }); });
  it.each(["REJECTED", "REMOVED"] as const)("does not let %s evidence block submission", async (status) => { const { deps, repository, workflow } = await completeDraft(); const at = new Date(); repository.addEvidenceFixture(workflow.fraudCase.id, { id: id(200), caseId: workflow.fraudCase.id, kind: "FILE", category: "OTHER_DOCUMENT", status, originalFilename: "synthetic.pdf", storageObjectKey: null, declaredMimeType: null, detectedMimeType: null, sizeBytes: null, sha256: null, inlineText: null, capturedAt: null, creationIdempotencyKey: null, uploadIdempotencyKey: null, uploadExpiresAt: null, validationStartedAt: null, uploadedAt: null, validatedAt: null, safeFailureCode: status === "REJECTED" ? "INVALID_FILE" : null, createdAt: at, updatedAt: at }); expect((await submitFraudCase({ caseId: workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, deps)).fraudCase.status).toBe("SUBMITTED"); });
  it("allows READY and FAILED extraction but requires review of COMPLETED", async () => { const value = await completeDraft(); const evidence = await addInlineEvidence({ caseId: value.workflow.fraudCase.id, kind: "PASTED_TEXT", category: "EMAIL", content: "Evidence", idempotencyKey: id(70) }, value.deps); const run = await createExtractionRun({ caseId: value.workflow.fraudCase.id, evidenceItemId: evidence.id, evidenceSha256: evidence.sha256!, idempotencyKey: id(71), provider: "fake", model: "m", modelVersion: "1", promptVersion: "v1", schemaVersion: "v1" }, value.deps); await claimExtractionRun(value.workflow.fraudCase.id, run.id, value.deps); await completeExtractionRun(value.workflow.fraudCase.id, run.id, output, value.deps); await expect(submitFraudCase({ caseId: value.workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, value.deps)).rejects.toMatchObject({ code: "CASE_SUBMISSION_BLOCKED" }); await reviewExtraction({ caseId: value.workflow.fraudCase.id, runId: run.id, status: "CONFIRMED" }, value.deps); expect((await submitFraudCase({ caseId: value.workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, value.deps)).fraudCase.status).toBe("SUBMITTED"); });
  it("rejects report/evidence mutation after submission", async () => { const { deps, workflow } = await completeDraft(); await submitFraudCase({ caseId: workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, deps); await expect(saveFraudCaseReport({ caseId: workflow.fraudCase.id, expectedVersion: 2, report: completeReport }, deps)).rejects.toMatchObject({ code: "FRAUD_CASE_ALREADY_SUBMITTED" }); await expect(addInlineEvidence({ caseId: workflow.fraudCase.id, kind: "CALL_NOTE", category: "CALL_NOTE", content: "Late", idempotencyKey: id(70) }, deps)).rejects.toMatchObject({ code: "FRAUD_CASE_ALREADY_SUBMITTED" }); });
  it("rejects evidence removal after submission without an event", async () => { const value = await completeDraft(); const evidence = await addInlineEvidence({ caseId: value.workflow.fraudCase.id, kind: "CALL_NOTE", category: "CALL_NOTE", content: "Before submission", idempotencyKey: id(70) }, value.deps); await submitFraudCase({ caseId: value.workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, value.deps); await expect(removeEvidence({ caseId: value.workflow.fraudCase.id, evidenceId: evidence.id }, value.deps)).rejects.toMatchObject({ code: "EVIDENCE_REMOVAL_NOT_ALLOWED" }); const latest = await value.repository.loadCase(value.workflow.fraudCase.id, context.accountId); expect(latest?.events.some((event) => event.eventType === "EVIDENCE_REMOVED")).toBe(false); });
  it("rejects extraction creation after submission without an event", async () => { const value = await completeDraft(); const evidence = await addInlineEvidence({ caseId: value.workflow.fraudCase.id, kind: "PASTED_TEXT", category: "EMAIL", content: "Before submission", idempotencyKey: id(70) }, value.deps); await submitFraudCase({ caseId: value.workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, value.deps); await expect(createExtractionRun({ caseId: value.workflow.fraudCase.id, evidenceItemId: evidence.id, evidenceSha256: evidence.sha256!, idempotencyKey: id(71), provider: "fake", model: "m", modelVersion: "1", promptVersion: "v1", schemaVersion: "v1" }, value.deps)).rejects.toMatchObject({ code: "FRAUD_CASE_ALREADY_SUBMITTED" }); const latest = await value.repository.loadCase(value.workflow.fraudCase.id, context.accountId); expect(latest?.events.some((event) => event.eventType === "EXTRACTION_PENDING")).toBe(false); });
  it("rejects extraction transition and review after submission", async () => { const value = await completeDraft(); const evidence = await addInlineEvidence({ caseId: value.workflow.fraudCase.id, kind: "PASTED_TEXT", category: "EMAIL", content: "Before submission", idempotencyKey: id(70) }, value.deps); const run = await createExtractionRun({ caseId: value.workflow.fraudCase.id, evidenceItemId: evidence.id, evidenceSha256: evidence.sha256!, idempotencyKey: id(71), provider: "fake", model: "m", modelVersion: "1", promptVersion: "v1", schemaVersion: "v1" }, value.deps); await claimExtractionRun(value.workflow.fraudCase.id, run.id, value.deps); await failExtractionRun(value.workflow.fraudCase.id, run.id, "SYNTHETIC_FAILURE", value.deps); await submitFraudCase({ caseId: value.workflow.fraudCase.id, submissionIdempotencyKey: id(80) }, value.deps); await expect(claimExtractionRun(value.workflow.fraudCase.id, run.id, value.deps)).rejects.toMatchObject({ code: "FRAUD_CASE_ALREADY_SUBMITTED" }); await expect(reviewExtraction({ caseId: value.workflow.fraudCase.id, runId: run.id, status: "CONFIRMED" }, value.deps)).rejects.toMatchObject({ code: "FRAUD_CASE_ALREADY_SUBMITTED" }); const latest = await value.repository.loadCase(value.workflow.fraudCase.id, context.accountId); expect(latest?.events.at(-1)?.eventType).toBe("CASE_SUBMITTED"); });
});
