import { describe, expect, it } from "vitest";

import { buildFinalEvidenceObjectLocator } from "../../evidence/application/evidence-object-keys";
import { MAX_EVIDENCE_FILE_BYTES, type EvidenceStatus } from "../../evidence/domain/evidence";
import { createOrResumeFraudCase } from "./create-or-resume-fraud-case";
import { removeEvidence } from "./manage-inline-evidence";
import {
  claimFileEvidenceValidation,
  createFileEvidence,
  finalizeFileEvidenceReady,
  finalizeFileEvidenceRejected,
  prepareFileEvidenceUploadGrant,
  reserveValidatedFileMetadata,
  retryStaleFileEvidenceValidation,
} from "./manage-file-evidence";
import { saveFraudCaseReport } from "./save-fraud-case-report";
import { submitFraudCase } from "./submit-fraud-case";
import { InMemoryFraudCaseRepository } from "./testing/in-memory-fraud-case-repository";
import type { EvidenceItemRecord } from "./fraud-case-types";

const context = { customerId: "10000000-0000-4000-8000-000000000001", accountId: "20000000-0000-4000-8000-000000000001" };
const paymentId = "40000000-0000-4000-8000-000000000001";
const id = (number: number) => `00000000-0000-4000-8000-${String(number).padStart(12, "0")}`;

function harness() {
  const repository = new InMemoryFraudCaseRepository(context, [{ id: paymentId, accountId: context.accountId, beneficiaryId: id(900), beneficiaryName: "Synthetic", amountMinor: 10_000, currencyCode: "GBP", reference: "Synthetic", status: "SETTLED", createdAt: new Date("2026-08-01T00:00:00Z") }]);
  let uuidValue = 1; let nowValue = Date.parse("2026-08-09T12:00:00.000Z");
  const deps = { repository, uuid: () => id(uuidValue++), now: () => new Date(nowValue++) };
  return { repository, deps, setNow: (value: Date) => { nowValue = value.getTime(); } };
}

async function draft() { const value = harness(); const workflow = await createOrResumeFraudCase(paymentId, value.deps); return { ...value, workflow }; }
const fileRequest = (caseId: string, keyNumber: number, overrides: Record<string, unknown> = {}) => ({ caseId, category: "EMAIL", originalFilename: " synthetic.png ", declaredMimeType: "image/png", uploadIdempotencyKey: id(keyNumber), ...overrides });

function fixture(caseId: string, number: number, input: { status?: EvidenceStatus; kind?: "FILE" | "CALL_NOTE"; sizeBytes?: number | null; validationToken?: Date | null } = {}): EvidenceItemRecord {
  const status = input.status ?? "READY"; const kind = input.kind ?? "FILE"; const at = new Date("2026-08-01T00:00:00Z");
  return { id: id(number), caseId, kind, category: kind === "FILE" ? "EMAIL" : "CALL_NOTE", status, originalFilename: kind === "FILE" ? `synthetic-${number}.png` : null, storageObjectKey: kind === "FILE" && (status === "READY" || input.sizeBytes != null) ? `sentinelpay/cases/${caseId}/evidence/${id(number)}/${"a".repeat(64)}/original` : null, declaredMimeType: kind === "FILE" ? "image/png" : null, detectedMimeType: kind === "FILE" && (status === "READY" || input.sizeBytes != null) ? "image/png" : null, sizeBytes: input.sizeBytes ?? (kind === "FILE" && status === "READY" ? 1 : null), sha256: kind === "FILE" && (status === "READY" || input.sizeBytes != null) ? "a".repeat(64) : kind === "CALL_NOTE" ? "b".repeat(64) : null, inlineText: kind === "CALL_NOTE" ? "Synthetic note" : null, capturedAt: null, creationIdempotencyKey: kind === "CALL_NOTE" ? id(700 + number) : null, uploadIdempotencyKey: kind === "FILE" ? id(800 + number) : null, uploadExpiresAt: null, validationStartedAt: status === "VALIDATING" ? (input.validationToken ?? at) : null, uploadedAt: status === "VALIDATING" ? at : null, validatedAt: status === "READY" || status === "REJECTED" ? at : null, safeFailureCode: status === "REJECTED" ? "FILE_TYPE_UNSUPPORTED" : null, createdAt: at, updatedAt: at };
}

async function createdAndClaimed(keyNumber = 100) {
  const value = await draft();
  const evidence = await createFileEvidence(fileRequest(value.workflow.fraudCase.id, keyNumber), value.deps);
  const claim = await claimFileEvidenceValidation({ caseId: value.workflow.fraudCase.id, evidenceId: evidence.id }, value.deps);
  if (claim.kind !== "CLAIMED") throw new Error("Expected claim");
  return { ...value, evidence: claim.evidence, token: claim.validationToken };
}

describe("FILE evidence creation and grant preparation", () => {
  it("creates normalized AWAITING_UPLOAD evidence and one safe event", async () => { const { deps, repository, workflow } = await draft(); const evidence = await createFileEvidence(fileRequest(workflow.fraudCase.id, 100, { originalFilename: " Cafe\u0301.png " }), deps); expect(evidence).toMatchObject({ status: "AWAITING_UPLOAD", originalFilename: "Café.png", storageObjectKey: null, detectedMimeType: null, sizeBytes: null, sha256: null, uploadIdempotencyKey: id(100) }); const loaded = await repository.loadCase(workflow.fraudCase.id, context.accountId); expect(loaded?.events.at(-1)).toMatchObject({ eventType: "EVIDENCE_UPLOAD_REQUESTED", actorType: "CUSTOMER", eventSequence: 2, metadata: { simulation: true } }); });
  it("returns an identical retry and rejects a changed canonical payload", async () => { const { deps, repository, workflow } = await draft(); const request = fileRequest(workflow.fraudCase.id, 100, { capturedAt: null }); const first = await createFileEvidence(request, deps); expect((await createFileEvidence(request, deps)).id).toBe(first.id); await expect(createFileEvidence({ ...request, declaredMimeType: "image/jpeg" }, deps)).rejects.toMatchObject({ code: "EVIDENCE_IDEMPOTENCY_CONFLICT" }); expect((await repository.loadCase(workflow.fraudCase.id, context.accountId))?.evidenceItems).toHaveLength(1); });
  it("enforces five active FILE items and excludes REMOVED", async () => { const value = await draft(); const files = []; for (let index = 0; index < 5; index++) files.push(await createFileEvidence(fileRequest(value.workflow.fraudCase.id, 100 + index), value.deps)); await expect(createFileEvidence(fileRequest(value.workflow.fraudCase.id, 106), value.deps)).rejects.toMatchObject({ code: "FILE_EVIDENCE_LIMIT_REACHED" }); await removeEvidence({ caseId: value.workflow.fraudCase.id, evidenceId: files[0].id }, value.deps); await expect(createFileEvidence(fileRequest(value.workflow.fraudCase.id, 107), value.deps)).resolves.toMatchObject({ status: "AWAITING_UPLOAD" }); });
  it("allows a fifth FILE when only four are active", async () => { const value = await draft(); for (let index = 0; index < 4; index++) await createFileEvidence(fileRequest(value.workflow.fraudCase.id, 100 + index), value.deps); await expect(createFileEvidence(fileRequest(value.workflow.fraudCase.id, 104), value.deps)).resolves.toMatchObject({ status: "AWAITING_UPLOAD" }); });
  it("allows the tenth active item, rejects the eleventh, and ignores REMOVED", async () => { const value = await draft(); for (let index = 0; index < 9; index++) value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 300 + index, { kind: "CALL_NOTE" })); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 400, { kind: "CALL_NOTE", status: "REMOVED" })); await expect(createFileEvidence(fileRequest(value.workflow.fraudCase.id, 100), value.deps)).resolves.toMatchObject({ status: "AWAITING_UPLOAD" }); await expect(createFileEvidence(fileRequest(value.workflow.fraudCase.id, 101), value.deps)).rejects.toMatchObject({ code: "EVIDENCE_LIMIT_REACHED" }); });
  it("prepares and reissues trusted grant data without a storage call", async () => { const { deps, workflow } = await draft(); const evidence = await createFileEvidence(fileRequest(workflow.fraudCase.id, 100), deps); const first = await prepareFileEvidenceUploadGrant({ caseId: workflow.fraudCase.id, evidenceId: evidence.id }, deps); const second = await prepareFileEvidenceUploadGrant({ caseId: workflow.fraudCase.id, evidenceId: evidence.id }, deps); expect(first.uploadSessionId).toBe(id(100)); expect(first.locator).toBe(`sentinelpay/quarantine/${id(100)}`); expect(second.expiresAt.getTime()).toBeGreaterThan(first.expiresAt.getTime()); });
});

describe("FILE validation ownership", () => {
  it("claims once, persists the exact token and returns IN_PROGRESS on duplicate", async () => { const value = await createdAndClaimed(); expect(value.evidence).toMatchObject({ status: "VALIDATING", validationStartedAt: value.token, uploadedAt: value.token }); const duplicate = await claimFileEvidenceValidation({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id }, value.deps); expect(duplicate.kind).toBe("IN_PROGRESS"); expect((await value.repository.loadCase(value.workflow.fraudCase.id, context.accountId))?.events.filter((item) => item.eventType === "EVIDENCE_VALIDATION_STARTED")).toHaveLength(1); });
  it("does not reclaim a fresh token and replaces a stale token by at least one millisecond", async () => { const value = await createdAndClaimed(); expect((await retryStaleFileEvidenceValidation({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id }, value.deps)).kind).toBe("IN_PROGRESS"); value.setNow(new Date(value.token.getTime() + 10 * 60_000)); const reclaimed = await retryStaleFileEvidenceValidation({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id }, value.deps); expect(reclaimed.kind).toBe("RECLAIMED"); if (reclaimed.kind !== "RECLAIMED") return; expect(reclaimed.validationToken.getTime()).toBeGreaterThan(value.token.getTime()); expect((await value.repository.loadCase(value.workflow.fraudCase.id, context.accountId))?.events.filter((item) => item.eventType === "EVIDENCE_VALIDATION_RESTARTED")).toHaveLength(1); });
  it.each(["READY", "REJECTED"] as const)("returns an existing %s outcome without another event", async (status) => { const value = await draft(); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 500, { status })); const result = await claimFileEvidenceValidation({ caseId: value.workflow.fraudCase.id, evidenceId: id(500) }, value.deps); expect(result.kind).toBe(status); });
  it("rejects REMOVED evidence", async () => { const value = await draft(); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 500, { status: "REMOVED" })); await expect(claimFileEvidenceValidation({ caseId: value.workflow.fraudCase.id, evidenceId: id(500) }, value.deps)).rejects.toMatchObject({ code: "EVIDENCE_NOT_AWAITING_UPLOAD" }); });
});

describe("FILE metadata reservation and terminal persistence", () => {
  function metadata(caseId: string, evidenceId: string, sizeBytes = 10) { const sha256 = "c".repeat(64); return { sizeBytes, detectedMimeType: "image/png", sha256, finalLocator: buildFinalEvidenceObjectLocator({ caseId, evidenceId, sha256 }) }; }
  it("reserves trusted metadata without an event and replaces its own reservation", async () => { const value = await createdAndClaimed(); const before = (await value.repository.loadCase(value.workflow.fraudCase.id, context.accountId))!.events.length; const first = await reserveValidatedFileMetadata({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, ...metadata(value.workflow.fraudCase.id, value.evidence.id) }, value.deps); expect(first).toMatchObject({ kind: "RESERVED", evidence: { status: "VALIDATING", sizeBytes: 10 } }); const replacement = await reserveValidatedFileMetadata({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, ...metadata(value.workflow.fraudCase.id, value.evidence.id, 11) }, value.deps); expect(replacement).toMatchObject({ kind: "RESERVED", evidence: { sizeBytes: 11 } }); expect((await value.repository.loadCase(value.workflow.fraudCase.id, context.accountId))!.events).toHaveLength(before); });
  it("permits exactly 20 MiB and rejects one byte above it", async () => { const exact = await createdAndClaimed(); for (let index = 0; index < 3; index++) exact.repository.addEvidenceFixture(exact.workflow.fraudCase.id, fixture(exact.workflow.fraudCase.id, 500 + index, { sizeBytes: MAX_EVIDENCE_FILE_BYTES })); await expect(reserveValidatedFileMetadata({ caseId: exact.workflow.fraudCase.id, evidenceId: exact.evidence.id, validationToken: exact.token, ...metadata(exact.workflow.fraudCase.id, exact.evidence.id, MAX_EVIDENCE_FILE_BYTES) }, exact.deps)).resolves.toMatchObject({ kind: "RESERVED" }); const overflow = await createdAndClaimed(); for (let index = 0; index < 4; index++) overflow.repository.addEvidenceFixture(overflow.workflow.fraudCase.id, fixture(overflow.workflow.fraudCase.id, 600 + index, { sizeBytes: MAX_EVIDENCE_FILE_BYTES })); await expect(reserveValidatedFileMetadata({ caseId: overflow.workflow.fraudCase.id, evidenceId: overflow.evidence.id, validationToken: overflow.token, ...metadata(overflow.workflow.fraudCase.id, overflow.evidence.id, 1) }, overflow.deps)).resolves.toMatchObject({ kind: "REJECTED", evidence: { safeFailureCode: "CASE_FILE_BYTES_LIMIT_EXCEEDED", sizeBytes: null } }); });
  it("counts READY and other reserved VALIDATING bytes but excludes other states", async () => { const value = await createdAndClaimed(); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 501, { sizeBytes: MAX_EVIDENCE_FILE_BYTES })); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 502, { status: "VALIDATING", sizeBytes: MAX_EVIDENCE_FILE_BYTES })); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 503, { status: "AWAITING_UPLOAD" })); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 504, { status: "REJECTED" })); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 505, { status: "REMOVED", sizeBytes: MAX_EVIDENCE_FILE_BYTES })); await expect(reserveValidatedFileMetadata({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, ...metadata(value.workflow.fraudCase.id, value.evidence.id, MAX_EVIDENCE_FILE_BYTES) }, value.deps)).resolves.toMatchObject({ kind: "RESERVED" }); });
  it("serializes the feasible 14 MiB + 3 MiB + 4 MiB boundary", async () => { const value = await createdAndClaimed(); const second = fixture(value.workflow.fraudCase.id, 502, { status: "VALIDATING", validationToken: value.token }); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 500, { sizeBytes: 5 * 1024 * 1024 })); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, fixture(value.workflow.fraudCase.id, 501, { sizeBytes: 5 * 1024 * 1024 })); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, { ...fixture(value.workflow.fraudCase.id, 503, { sizeBytes: 4 * 1024 * 1024 }) }); value.repository.addEvidenceFixture(value.workflow.fraudCase.id, second); await expect(reserveValidatedFileMetadata({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, ...metadata(value.workflow.fraudCase.id, value.evidence.id, 3 * 1024 * 1024) }, value.deps)).resolves.toMatchObject({ kind: "RESERVED" }); await expect(reserveValidatedFileMetadata({ caseId: value.workflow.fraudCase.id, evidenceId: second.id, validationToken: value.token, ...metadata(value.workflow.fraudCase.id, second.id, 4 * 1024 * 1024) }, value.deps)).resolves.toMatchObject({ kind: "REJECTED" }); });
  it("prevents an old worker after reclaim and rejects malformed or arbitrary locator metadata", async () => { const value = await createdAndClaimed(); value.setNow(new Date(value.token.getTime() + 10 * 60_000)); const reclaimed = await retryStaleFileEvidenceValidation({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id }, value.deps); expect(reclaimed.kind).toBe("RECLAIMED"); await expect(reserveValidatedFileMetadata({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, ...metadata(value.workflow.fraudCase.id, value.evidence.id) }, value.deps)).rejects.toMatchObject({ code: "EVIDENCE_VALIDATION_CONFLICT" }); await expect(reserveValidatedFileMetadata({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: reclaimed.kind === "RECLAIMED" ? reclaimed.validationToken : value.token, ...metadata(value.workflow.fraudCase.id, value.evidence.id), finalLocator: "arbitrary" }, value.deps)).rejects.toMatchObject({ code: "INVALID_FILE_EVIDENCE_METADATA" }); });
  it("finalizes READY idempotently with safe metadata and no duplicate event", async () => { const value = await createdAndClaimed(); const values = metadata(value.workflow.fraudCase.id, value.evidence.id); await reserveValidatedFileMetadata({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, ...values }, value.deps); const first = await finalizeFileEvidenceReady({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, ...values, pdfPageCount: null }, value.deps); const retry = await finalizeFileEvidenceReady({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, ...values }, value.deps); expect(first.status).toBe("READY"); expect(retry.id).toBe(first.id); const loaded = await value.repository.loadCase(value.workflow.fraudCase.id, context.accountId); expect(loaded?.events.filter((item) => item.eventType === "EVIDENCE_VALIDATED")).toHaveLength(1); expect(JSON.stringify(loaded?.events.at(-1)?.metadata)).not.toMatch(/storage|hash|filename|provider/iu); });
  it("rejects using an allowlisted code, clears reservation and is idempotent", async () => { const value = await createdAndClaimed(); await reserveValidatedFileMetadata({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, ...metadata(value.workflow.fraudCase.id, value.evidence.id) }, value.deps); const first = await finalizeFileEvidenceRejected({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, safeFailureCode: "PDF_INVALID" }, value.deps); const retry = await finalizeFileEvidenceRejected({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, safeFailureCode: "PDF_INVALID" }, value.deps); expect(first).toMatchObject({ status: "REJECTED", storageObjectKey: null, sizeBytes: null, safeFailureCode: "PDF_INVALID" }); expect(retry.id).toBe(first.id); expect((await value.repository.loadCase(value.workflow.fraudCase.id, context.accountId))?.events.filter((item) => item.eventType === "EVIDENCE_REJECTED")).toHaveLength(1); await expect(finalizeFileEvidenceRejected({ caseId: value.workflow.fraudCase.id, evidenceId: value.evidence.id, validationToken: value.token, safeFailureCode: "raw provider failure" }, value.deps)).rejects.toMatchObject({ code: "INVALID_FILE_EVIDENCE_METADATA" }); });
});

describe("FILE submission interaction", () => {
  it("continues to block submission while FILE evidence is incomplete", async () => { const value = await draft(); const evidence = await createFileEvidence(fileRequest(value.workflow.fraudCase.id, 100), value.deps); await saveFraudCaseReport({ caseId: value.workflow.fraudCase.id, expectedVersion: 1, report: { suspectedScamCategory: "OTHER", believedPaymentPurpose: "Synthetic purpose", contactChannel: "EMAIL", discoveredAt: new Date("2026-08-01T00:00:00Z"), discoveryReason: "Synthetic discovery reason", narrative: "A sufficiently long synthetic narrative for submission.", pressureOrUrgency: "NO", guaranteedReturns: "NO", toldToIgnoreWarnings: "NO", remoteAccessRequested: "NO", additionalSupportRequested: false } }, value.deps); await expect(submitFraudCase({ caseId: value.workflow.fraudCase.id, submissionIdempotencyKey: id(999) }, value.deps)).rejects.toMatchObject({ code: "CASE_SUBMISSION_BLOCKED" }); await claimFileEvidenceValidation({ caseId: value.workflow.fraudCase.id, evidenceId: evidence.id }, value.deps); await expect(submitFraudCase({ caseId: value.workflow.fraudCase.id, submissionIdempotencyKey: id(998) }, value.deps)).rejects.toMatchObject({ code: "CASE_SUBMISSION_BLOCKED" }); });
});
