import { and, asc, eq, sql } from "drizzle-orm";
import type { NeonHttpDatabase } from "drizzle-orm/neon-http";
import { getDatabase } from "@/db/client";
import { accounts, beneficiaries, caseEvents, customers, evidenceExtractionReviews, evidenceExtractionRuns, evidenceItems, fraudCaseReports, fraudCases, payments } from "@/db/schema";
import type * as schema from "@/db/schema";
import { parseExtractionResult } from "../../evidence/domain/extraction";
import { FraudCaseApplicationError } from "../application/fraud-case-application-errors";
import type { AddEvidenceResult, AtomicResult, CreateCaseResult, CreateExtractionResult, CreateReviewResult, FraudCaseRepository } from "../application/fraud-case-repository";
import type { AddInlineEvidenceCommand, ExtractionReviewRecord, ExtractionRunRecord, ExtractionTransitionCommand, FraudCaseWorkflow, NewCaseEvent, NewFraudCaseWorkflow, RemoveEvidenceCommand, SaveReportCommand, SubmitCaseCommand } from "../application/fraud-case-types";

type Database = NeonHttpDatabase<typeof schema>;
const DEMO_EMAIL = "demo.customer@sentinelpay.local";
const CASE_PAYMENT_INDEX = "fraud_cases_payment_id_idx";
const EVIDENCE_CREATION_INDEX = "evidence_items_creation_idempotency_key_idx";
const EXTRACTION_KEY_INDEX = "evidence_extraction_runs_idempotency_key_idx";
const COMPLETED_EXTRACTION_INDEX = "evidence_extraction_runs_one_completed_idx";
const ACTIVE_EXTRACTION_INDEX = "evidence_extraction_runs_one_active_idx";
const REVIEW_INDEX = "evidence_extraction_reviews_run_id_idx";
const SUBMISSION_KEY_INDEX = "fraud_cases_submission_idempotency_key_idx";
type DbError = { code?: unknown; constraint?: unknown; cause?: unknown };
function isObject(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null; }
export function isNamedUniqueViolation(error: unknown, constraint: string): boolean { let value = error; for (let i = 0; i < 4 && isObject(value); i += 1) { const shaped = value as DbError; if (shaped.code === "23505" && shaped.constraint === constraint) return true; value = shaped.cause; } return false; }
const uniqueViolation = isNamedUniqueViolation;
function affected(result: unknown): boolean { if (!isObject(result)) return false; const rows = result.rows; return Array.isArray(rows) && rows.length > 0; }

export class DrizzleFraudCaseRepository implements FraudCaseRepository {
  constructor(private readonly db: Database = getDatabase()) {}
  private nextEventSequence(caseId: string) { return sql`(select coalesce(max(${caseEvents.eventSequence}), 0) + 1 from ${caseEvents} where ${caseEvents.caseId}=${caseId})`; }
  private lockOwnedDraftCase(caseId: string, accountId: string) {
    return this.db.execute(sql`select ${fraudCases.id} from ${fraudCases} join ${payments} on ${payments.id}=${fraudCases.paymentId} join ${accounts} on ${accounts.id}=${payments.accountId} join ${customers} on ${customers.id}=${accounts.customerId} where ${fraudCases.id}=${caseId} and ${fraudCases.status}='DRAFT' and ${payments.accountId}=${accountId} and ${customers.email}=${DEMO_EMAIL} for update`);
  }
  async loadCustomerContext() { const [row] = await this.db.select({ customerId: customers.id, accountId: accounts.id }).from(customers).innerJoin(accounts, eq(accounts.customerId, customers.id)).where(eq(customers.email, DEMO_EMAIL)).orderBy(asc(accounts.createdAt)).limit(1); return row ?? null; }
  async loadOwnedPayment(paymentId: string, accountId: string) { const [row] = await this.db.select({ id: payments.id, accountId: payments.accountId, beneficiaryId: payments.beneficiaryId, beneficiaryName: beneficiaries.displayName, amountMinor: payments.amountMinor, currencyCode: payments.currencyCode, reference: payments.reference, status: payments.status, createdAt: payments.createdAt }).from(payments).innerJoin(beneficiaries, eq(beneficiaries.id, payments.beneficiaryId)).where(and(eq(payments.id, paymentId), eq(payments.accountId, accountId))).limit(1); return row ?? null; }
  async findCaseByPaymentId(paymentId: string, accountId: string) { const [row] = await this.db.select({ id: fraudCases.id }).from(fraudCases).innerJoin(payments, eq(payments.id, fraudCases.paymentId)).where(and(eq(fraudCases.paymentId, paymentId), eq(payments.accountId, accountId))).limit(1); return row ? this.loadCase(row.id, accountId) : null; }
  async loadCase(caseId: string, accountId: string): Promise<FraudCaseWorkflow | null> {
    const [base] = await this.db.select({ fraudCase: fraudCases, payment: { id: payments.id, accountId: payments.accountId, beneficiaryId: payments.beneficiaryId, beneficiaryName: beneficiaries.displayName, amountMinor: payments.amountMinor, currencyCode: payments.currencyCode, reference: payments.reference, status: payments.status, createdAt: payments.createdAt }, report: fraudCaseReports }).from(fraudCases).innerJoin(payments, eq(payments.id, fraudCases.paymentId)).innerJoin(beneficiaries, eq(beneficiaries.id, payments.beneficiaryId)).innerJoin(fraudCaseReports, eq(fraudCaseReports.caseId, fraudCases.id)).where(and(eq(fraudCases.id, caseId), eq(payments.accountId, accountId))).limit(1);
    if (!base) return null;
    const [evidence, runs, reviews, events] = await Promise.all([
      this.db.select().from(evidenceItems).where(eq(evidenceItems.caseId, caseId)).orderBy(asc(evidenceItems.createdAt), asc(evidenceItems.id)),
      this.db.select({ run: evidenceExtractionRuns }).from(evidenceExtractionRuns).innerJoin(evidenceItems, eq(evidenceItems.id, evidenceExtractionRuns.evidenceItemId)).where(eq(evidenceItems.caseId, caseId)).orderBy(asc(evidenceExtractionRuns.createdAt), asc(evidenceExtractionRuns.id)),
      this.db.select({ review: evidenceExtractionReviews }).from(evidenceExtractionReviews).innerJoin(evidenceExtractionRuns, eq(evidenceExtractionRuns.id, evidenceExtractionReviews.extractionRunId)).innerJoin(evidenceItems, eq(evidenceItems.id, evidenceExtractionRuns.evidenceItemId)).where(eq(evidenceItems.caseId, caseId)),
      this.db.select().from(caseEvents).where(eq(caseEvents.caseId, caseId)).orderBy(asc(caseEvents.eventSequence), asc(caseEvents.id)),
    ]);
    const mappedRuns: ExtractionRunRecord[] = runs.map(({ run }) => ({ ...run, machineOutput: run.machineOutput ? parseExtractionResult(run.machineOutput) : null }));
    const mappedReviews: ExtractionReviewRecord[] = reviews.map(({ review }) => ({ ...review, correctedOutput: review.correctedOutput ? parseExtractionResult(review.correctedOutput) : null }));
    return { fraudCase: base.fraudCase, payment: base.payment, report: base.report, evidenceItems: evidence, extractionRuns: mappedRuns, extractionReviews: mappedReviews, events };
  }
  async createCaseAtomically(workflow: NewFraudCaseWorkflow, accountId: string): Promise<CreateCaseResult> {
    const payment = await this.loadOwnedPayment(workflow.fraudCase.paymentId, accountId); if (!payment || payment.status !== "SETTLED") return { kind: "PAYMENT_RACE" };
    try { await this.db.batch([this.db.insert(fraudCases).values(workflow.fraudCase), this.db.insert(fraudCaseReports).values(workflow.report), this.db.insert(caseEvents).values({ ...workflow.event, eventSequence: 1 })]); return { kind: "CREATED" }; }
    catch (error) { if (isNamedUniqueViolation(error, CASE_PAYMENT_INDEX)) return { kind: "PAYMENT_RACE" }; throw new FraudCaseApplicationError("FRAUD_CASE_PERSISTENCE_CONFLICT"); }
  }
  async saveReportAtomically(command: SaveReportCommand): Promise<AtomicResult> {
    const mutation = this.db.execute(sql`with updated_report as (update ${fraudCaseReports} set "suspected_scam_category"=${command.report.suspectedScamCategory}, "believed_payment_purpose"=${command.report.believedPaymentPurpose}, "contact_channel"=${command.report.contactChannel}, "first_contact_at"=${command.report.firstContactAt}, "discovered_at"=${command.report.discoveredAt}, "discovery_reason"=${command.report.discoveryReason}, "narrative"=${command.report.narrative}, "pressure_or_urgency"=${command.report.pressureOrUrgency}, "guaranteed_returns"=${command.report.guaranteedReturns}, "told_to_ignore_warnings"=${command.report.toldToIgnoreWarnings}, "remote_access_requested"=${command.report.remoteAccessRequested}, "impersonated_organisation"=${command.report.impersonatedOrganisation}, "additional_support_requested"=${command.report.additionalSupportRequested}, "version"="version"+1, "updated_at"=${command.updatedAt} where "case_id"=${command.caseId} and "version"=${command.expectedVersion} and exists (select 1 from ${fraudCases} join ${payments} on ${payments.id}=${fraudCases.paymentId} where ${fraudCases.id}=${command.caseId} and ${fraudCases.status}='DRAFT' and ${payments.accountId}=${command.accountId}) returning "case_id"), updated_case as (update ${fraudCases} set "updated_at"=${command.updatedAt} where "id" in (select "case_id" from updated_report) and ${fraudCases.status}='DRAFT' returning "id") insert into ${caseEvents} ("id","case_id","event_sequence","event_type","actor_type","metadata","occurred_at") select ${command.event.id},"id",${this.nextEventSequence(command.caseId)},${command.event.eventType},${command.event.actorType},${JSON.stringify(command.event.metadata)}::jsonb,${command.event.occurredAt} from updated_case returning "id"`);
    try { const [, result] = await this.db.batch([this.lockOwnedDraftCase(command.caseId, command.accountId), mutation]); return affected(result) ? { kind: "APPLIED" } : { kind: "CONFLICT" }; }
    catch { throw new FraudCaseApplicationError("FRAUD_CASE_PERSISTENCE_CONFLICT"); }
  }
  async findEvidenceByCreationKey(key: string, accountId: string) { const [row] = await this.db.select({ evidence: evidenceItems }).from(evidenceItems).innerJoin(fraudCases, eq(fraudCases.id, evidenceItems.caseId)).innerJoin(payments, eq(payments.id, fraudCases.paymentId)).where(and(eq(evidenceItems.creationIdempotencyKey, key), eq(payments.accountId, accountId))).limit(1); return row?.evidence ?? null; }
  async addInlineEvidenceAtomically(command: AddInlineEvidenceCommand): Promise<AddEvidenceResult> {
    const lockCase = this.lockOwnedDraftCase(command.evidence.caseId, command.accountId);
    const insertEvidenceAndEvent = this.db.execute(sql`with inserted as (insert into ${evidenceItems} ("id","case_id","kind","category","status","sha256","inline_text","captured_at","creation_idempotency_key","validated_at","created_at","updated_at") select ${command.evidence.id},${command.evidence.caseId},${command.evidence.kind},${command.evidence.category},'READY',${command.evidence.sha256},${command.evidence.inlineText},${command.evidence.capturedAt},${command.evidence.creationIdempotencyKey},${command.evidence.validatedAt},${command.evidence.createdAt},${command.evidence.updatedAt} where (select count(*) from ${evidenceItems} where ${evidenceItems.caseId}=${command.evidence.caseId} and ${evidenceItems.status}<>'REMOVED') < 10 and exists (select 1 from ${fraudCases} join ${payments} on ${payments.id}=${fraudCases.paymentId} where ${fraudCases.id}=${command.evidence.caseId} and ${fraudCases.status}='DRAFT' and ${payments.accountId}=${command.accountId}) returning "id","case_id") insert into ${caseEvents} ("id","case_id","event_sequence","evidence_item_id","event_type","actor_type","request_idempotency_key","metadata","occurred_at") select ${command.event.id},"case_id",${this.nextEventSequence(command.evidence.caseId)},"id",${command.event.eventType},${command.event.actorType},${command.event.requestIdempotencyKey},${JSON.stringify(command.event.metadata)}::jsonb,${command.event.occurredAt} from inserted returning "id"`);
    try { const [locked, result] = await this.db.batch([lockCase, insertEvidenceAndEvent]); if (!affected(locked)) return { kind: "CONFLICT" }; return affected(result) ? { kind: "CREATED" } : { kind: "LIMIT" }; }
    catch (error) { if (isNamedUniqueViolation(error, EVIDENCE_CREATION_INDEX)) return { kind: "IDEMPOTENCY_RACE" }; throw new FraudCaseApplicationError("FRAUD_CASE_PERSISTENCE_CONFLICT"); }
  }
  async removeEvidenceAtomically(command: RemoveEvidenceCommand): Promise<AtomicResult> { const mutation = this.db.execute(sql`with updated as (update ${evidenceItems} set "status"='REMOVED',"updated_at"=${command.updatedAt} where "id"=${command.evidenceId} and "case_id"=${command.caseId} and "status"=${command.expectedStatus} and "status" in ('AWAITING_UPLOAD','READY','REJECTED') and exists (select 1 from ${fraudCases} join ${payments} on ${payments.id}=${fraudCases.paymentId} where ${fraudCases.id}=${command.caseId} and ${fraudCases.status}='DRAFT' and ${payments.accountId}=${command.accountId}) returning "id","case_id") insert into ${caseEvents} ("id","case_id","event_sequence","evidence_item_id","event_type","actor_type","metadata","occurred_at") select ${command.event.id},"case_id",${this.nextEventSequence(command.caseId)},"id",${command.event.eventType},${command.event.actorType},${JSON.stringify(command.event.metadata)}::jsonb,${command.event.occurredAt} from updated returning "id"`); try { const [, result] = await this.db.batch([this.lockOwnedDraftCase(command.caseId, command.accountId), mutation]); return affected(result) ? { kind: "APPLIED" } : { kind: "CONFLICT" }; } catch { throw new FraudCaseApplicationError("FRAUD_CASE_PERSISTENCE_CONFLICT"); } }
  async findExtractionByIdempotencyKey(key: string, accountId: string) { const [row] = await this.db.select({ run: evidenceExtractionRuns }).from(evidenceExtractionRuns).innerJoin(evidenceItems, eq(evidenceItems.id, evidenceExtractionRuns.evidenceItemId)).innerJoin(fraudCases, eq(fraudCases.id, evidenceItems.caseId)).innerJoin(payments, eq(payments.id, fraudCases.paymentId)).where(and(eq(evidenceExtractionRuns.idempotencyKey, key), eq(payments.accountId, accountId))).limit(1); return row ? { ...row.run, machineOutput: row.run.machineOutput ? parseExtractionResult(row.run.machineOutput) : null } : null; }
  async createExtractionRunAtomically(run: ExtractionRunRecord, caseId: string, accountId: string, event: NewCaseEvent): Promise<CreateExtractionResult> { const mutation = this.db.execute(sql`with inserted as (insert into ${evidenceExtractionRuns} ("id","evidence_item_id","evidence_sha256","status","idempotency_key","provider","model","model_version","prompt_version","schema_version","created_at") select ${run.id},${run.evidenceItemId},${run.evidenceSha256},'PENDING',${run.idempotencyKey},${run.provider},${run.model},${run.modelVersion},${run.promptVersion},${run.schemaVersion},${run.createdAt} where exists (select 1 from ${evidenceItems} join ${fraudCases} on ${fraudCases.id}=${evidenceItems.caseId} join ${payments} on ${payments.id}=${fraudCases.paymentId} where ${evidenceItems.id}=${run.evidenceItemId} and ${evidenceItems.caseId}=${caseId} and ${evidenceItems.status}='READY' and ${evidenceItems.sha256}=${run.evidenceSha256} and ${fraudCases.status}='DRAFT' and ${payments.accountId}=${accountId}) and not exists (select 1 from ${evidenceExtractionRuns} where ${evidenceExtractionRuns.evidenceItemId}=${run.evidenceItemId} and ${evidenceExtractionRuns.evidenceSha256}=${run.evidenceSha256} and ${evidenceExtractionRuns.status} in ('PENDING','PROCESSING','COMPLETED')) returning "id") insert into ${caseEvents} ("id","case_id","event_sequence","evidence_item_id","event_type","actor_type","request_idempotency_key","metadata","occurred_at") select ${event.id},${caseId},${this.nextEventSequence(caseId)},${run.evidenceItemId},${event.eventType},${event.actorType},${event.requestIdempotencyKey},${JSON.stringify(event.metadata)}::jsonb,${event.occurredAt} from inserted returning "id"`); try { const [, result] = await this.db.batch([this.lockOwnedDraftCase(caseId, accountId), mutation]); return affected(result) ? { kind: "CREATED" } : { kind: "CONFLICT" }; } catch (error) { if (uniqueViolation(error, EXTRACTION_KEY_INDEX)) return { kind: "IDEMPOTENCY_RACE" }; if (uniqueViolation(error, ACTIVE_EXTRACTION_INDEX)) return { kind: "CONFLICT" }; throw new FraudCaseApplicationError("FRAUD_CASE_PERSISTENCE_CONFLICT"); } }
  async transitionExtractionAtomically(command: ExtractionTransitionCommand): Promise<AtomicResult> { const mutation = this.db.execute(sql`with updated as (update ${evidenceExtractionRuns} set "status"=${command.run.status},"started_at"=${command.run.startedAt},"completed_at"=${command.run.completedAt},"machine_output"=${command.run.machineOutput ? JSON.stringify(command.run.machineOutput) : null}::jsonb,"safe_failure_code"=${command.run.safeFailureCode} where "id"=${command.runId} and "status"=${command.fromStatus} and exists (select 1 from ${evidenceItems} join ${fraudCases} on ${fraudCases.id}=${evidenceItems.caseId} join ${payments} on ${payments.id}=${fraudCases.paymentId} where ${evidenceItems.id}=${evidenceExtractionRuns.evidenceItemId} and ${evidenceItems.caseId}=${command.caseId} and ${evidenceItems.sha256}=${evidenceExtractionRuns.evidenceSha256} and ${fraudCases.status}='DRAFT' and ${payments.accountId}=${command.accountId}) returning "evidence_item_id"), inserted as (insert into ${caseEvents} ("id","case_id","event_sequence","evidence_item_id","event_type","actor_type","metadata","occurred_at") select ${command.event.id},${command.caseId},${this.nextEventSequence(command.caseId)},"evidence_item_id",${command.event.eventType},${command.event.actorType},${JSON.stringify(command.event.metadata)}::jsonb,${command.event.occurredAt} from updated returning "id") select "id" from inserted`); try { const [, result] = await this.db.batch([this.lockOwnedDraftCase(command.caseId, command.accountId), mutation]); return affected(result) ? { kind: "APPLIED" } : { kind: "CONFLICT" }; } catch (error) { if (uniqueViolation(error, COMPLETED_EXTRACTION_INDEX) || uniqueViolation(error, ACTIVE_EXTRACTION_INDEX)) return { kind: "CONFLICT" }; throw new FraudCaseApplicationError("FRAUD_CASE_PERSISTENCE_CONFLICT"); } }
  async createExtractionReviewAtomically(review: ExtractionReviewRecord, caseId: string, accountId: string, event: NewCaseEvent): Promise<CreateReviewResult> { const mutation = this.db.execute(sql`with inserted as (insert into ${evidenceExtractionReviews} ("id","extraction_run_id","status","corrected_output","reviewed_at") select ${review.id},${review.extractionRunId},${review.status},${review.correctedOutput ? JSON.stringify(review.correctedOutput) : null}::jsonb,${review.reviewedAt} where exists (select 1 from ${evidenceExtractionRuns} join ${evidenceItems} on ${evidenceItems.id}=${evidenceExtractionRuns.evidenceItemId} join ${fraudCases} on ${fraudCases.id}=${evidenceItems.caseId} join ${payments} on ${payments.id}=${fraudCases.paymentId} where ${evidenceExtractionRuns.id}=${review.extractionRunId} and ${evidenceExtractionRuns.status}='COMPLETED' and ${fraudCases.id}=${caseId} and ${fraudCases.status}='DRAFT' and ${payments.accountId}=${accountId}) returning "extraction_run_id") insert into ${caseEvents} ("id","case_id","event_sequence","evidence_item_id","event_type","actor_type","metadata","occurred_at") select ${event.id},${caseId},${this.nextEventSequence(caseId)},${event.evidenceItemId},${event.eventType},${event.actorType},${JSON.stringify(event.metadata)}::jsonb,${event.occurredAt} from inserted returning "id"`); try { const [, result] = await this.db.batch([this.lockOwnedDraftCase(caseId, accountId), mutation]); return affected(result) ? { kind: "CREATED" } : { kind: "CONFLICT" }; } catch (error) { if (uniqueViolation(error, REVIEW_INDEX)) return { kind: "EXISTS" }; throw new FraudCaseApplicationError("FRAUD_CASE_PERSISTENCE_CONFLICT"); } }
  async submitCaseAtomically(command: SubmitCaseCommand): Promise<AtomicResult> { const mutation = this.db.execute(sql`with eligible as (select ${fraudCases.id} from ${fraudCases} join ${payments} on ${payments.id}=${fraudCases.paymentId} join ${fraudCaseReports} on ${fraudCaseReports.caseId}=${fraudCases.id} where ${fraudCases.id}=${command.caseId} and ${fraudCases.status}='DRAFT' and ${payments.accountId}=${command.accountId} and ${payments.status}='SETTLED' and ${fraudCaseReports.version}=${command.expectedReportVersion} and ${fraudCaseReports.suspectedScamCategory} is not null and ${fraudCaseReports.believedPaymentPurpose} is not null and ${fraudCaseReports.contactChannel} is not null and ${fraudCaseReports.discoveredAt} is not null and ${fraudCaseReports.discoveryReason} is not null and ${fraudCaseReports.narrative} is not null and ${fraudCaseReports.pressureOrUrgency} is not null and ${fraudCaseReports.guaranteedReturns} is not null and ${fraudCaseReports.toldToIgnoreWarnings} is not null and ${fraudCaseReports.remoteAccessRequested} is not null and ${fraudCaseReports.additionalSupportRequested} is not null and not exists (select 1 from ${evidenceItems} where ${evidenceItems.caseId}=${command.caseId} and ${evidenceItems.status}<>'REMOVED' and ${evidenceItems.status} in ('AWAITING_UPLOAD','VALIDATING')) and not exists (select 1 from ${evidenceExtractionRuns} join ${evidenceItems} on ${evidenceItems.id}=${evidenceExtractionRuns.evidenceItemId} left join ${evidenceExtractionReviews} on ${evidenceExtractionReviews.extractionRunId}=${evidenceExtractionRuns.id} where ${evidenceItems.caseId}=${command.caseId} and ${evidenceExtractionRuns.status}='COMPLETED' and ${evidenceExtractionReviews.id} is null)), updated as (update ${fraudCases} set "status"='SUBMITTED',"submitted_at"=${command.submittedAt},"updated_at"=${command.submittedAt},"submission_idempotency_key"=${command.idempotencyKey} where "id" in (select "id" from eligible) and ${fraudCases.status}='DRAFT' returning "id") insert into ${caseEvents} ("id","case_id","event_sequence","event_type","actor_type","request_idempotency_key","metadata","occurred_at") select ${command.event.id},"id",${this.nextEventSequence(command.caseId)},${command.event.eventType},${command.event.actorType},${command.idempotencyKey},${JSON.stringify(command.event.metadata)}::jsonb,${command.event.occurredAt} from updated returning "id"`); try { const [, result] = await this.db.batch([this.lockOwnedDraftCase(command.caseId, command.accountId), mutation]); return affected(result) ? { kind: "APPLIED" } : { kind: "CONFLICT" }; } catch (error) { if (uniqueViolation(error, SUBMISSION_KEY_INDEX)) throw new FraudCaseApplicationError("FRAUD_CASE_PERSISTENCE_CONFLICT"); throw new FraudCaseApplicationError("FRAUD_CASE_PERSISTENCE_CONFLICT"); } }
}
